version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker login --username AWS --password $(aws ecr get-login-password --region us-east-1) | 356223155086.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t ts-tsc/node-ec2:latest .
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker push ts-tsc/node-ec2:latest
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
