export default {
"data" : {
  "employees": [
    {
      "id": "1",
      "name": "First Person",
      "firstName": "First",
      "lastName": "Person",
      "preferredName": null,
      "displayName": "First Person",
      "department": "IT",
      "jobTitle": "IT Support Specialist",
      "location": "Durham",
      "pronouns": "He/Him",
      "photoUrl": "https://randomuser.me/api/portraits/lego/1.jpg",
      "supervisor": "Tobias Dengel",
      "allocations": [],
      "skills": ["Being First", "Not Being Last"],
      "pronunciation": "Per-son",
      "branch": "Roots",
      "employeeStatus": "default",
      "PTOStart": null,
      "PTOEnd": null,
      "hireDate": "2015-06-16",
      "supervisorId": "51",
      "supervisorEmail": "tobias.dengel@willowtreeapps.com",
      "state": "North Carolina",
      "city": "Raleigh",
      "email": "first.person@willowtreeapps.com",
      "newHireMentor": "Jon Smoth",
      "longTermMentor": null,
      "slackId": "U1111ABCD"
    },
    {
      "id": "3",
      "name": "Third Human",
      "firstName": "Third",
      "lastName": "Human",
      "preferredName": "Three",
      "displayName": "Three Human",
      "department": "Software Engineering",
      "jobTitle": "Software Test Engineer",
      "location": "Durham",
      "pronouns": "She/Her",
      "photoUrl": "https://randomuser.me/api/portraits/lego/7.jpg",
      "supervisor": "Two Person",
      "allocations": [],
      "skills": [],
      "pronunciation": null,
      "branch": "Sycamore",
      "employeeStatus": "default",
      "PTOStart": null,
      "PTOEnd": null,
      "hireDate": "2017-03-22",
      "supervisorId": "2",
      "supervisorEmail": "second.person@willowtreeapps.com",
      "state": "North Carolina",
      "city": "Durham",
      "email": "third.human@willowtreeapps.com",
      "newHireMentor": null,
      "longTermMentor": "Jan Dine",
      "slackId": "U2222ABCD"
    },
    {
      "id": "51",
      "name": "Tobias Dengel",
      "firstName": "Tobias",
      "lastName": "Dengel",
      "preferredName": null,
      "displayName": "Tobias Dengel",
      "department": "Executive",
      "jobTitle": "Chief Executive Officer",
      "location": "Charlottesville",
      "pronouns": "He/Him",
      "photoUrl": "https://randomuser.me/api/portraits/lego/5.jpg",
      "supervisor": null,
      "allocations": [],
      "skills": [
        "Marketing Strategy",
        "Branding",
        "Design Thinking",
        "Leadership"
      ],
      "pronunciation": null,
      "branch": null,
      "employeeStatus": "leave",
      "PTOStart": "2000-01-01",
      "PTOEnd": "2100-01-01",
      "hireDate": "2010-05-01",
      "supervisorId": null,
      "supervisorEmail": null,
      "state": "Virginia",
      "city": "Charlottesville",
      "email": "tobias.dengel@willowtreeapps.com",
      "newHireMentor": "Jon Smoth",
      "longTermMentor": "Jan Dine",
      "slackId": "U4444ABCD"
    },
    {
      "id": "2",
      "name": "Second Person",
      "firstName": "Second",
      "lastName": "Person",
      "preferredName": "Two",
      "displayName": "Two Person",
      "department": "Intern",
      "jobTitle": "Product Designer - Intern",
      "location": "Columbus",
      "pronouns": "He/Him",
      "photoUrl": "https://randomuser.me/api/portraits/lego/7.jpg",
      "supervisor": "First Person",
      "allocations": [
        {
          "client": "Mastercard",
          "project": "Mastercard - SmartData Program 2022"
        }
      ],
      "skills": [],
      "pronunciation": null,
      "branch": "Sycamore",
      "employeeStatus": "default",
      "PTOStart": null,
      "PTOEnd": null,
      "hireDate": "2017-02-10",
      "supervisorId": "1",
      "supervisorEmail": "first.person@willowtreeapps.com",
      "state": "Ohio",
      "city": "Columbus",
      "email": "second.person@willowtreeapps.com",
      "newHireMentor": null,
      "longTermMentor": "Jan Dine",
      "slackId": "U3333ABCD"
    }
  ]
}

}