name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID: 
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true
env:
  ECR_REGISTRY: 356223155086.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: ts-tsc
  AWS_REGION: us-east-1
  ECR_IMAGE_TAG: node-ec2
  EC2_PUB_IP: ec2-54-198-98-185.compute-1.amazonaws.com
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ github.event.inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ github.event.inputs.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ github.event.inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ env.AWS_REGION }}
      - name: Build and push Docker image
        id: build-image
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.ECR_IMAGE_TAG }} .
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.ECR_IMAGE_TAG }}
        shell: bash
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ EC2_PUB_IP }}
          username: ec2-user
          key: ${{ env.SSH_KEY }}

      - name: Pull Docker image on EC2 instance
        run: |
          ssh ec2-user@${{ EC2_PUB_IP }} 'docker pull ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:{{ env.ECR_IMAGE_TAG }}'
      - name: Stop running containers on EC2 instance
        run: |
          ssh ec2-user@${{ EC2_PUB_IP }} 'docker stop $(docker ps -aq) || true'
      - name: Remove stopped containers on EC2 instance
        run: |
          ssh ec2-user@${{ EC2_PUB_IP }} 'docker rm $(docker ps -aq) || true'
      - name: Run Docker container on EC2 instance
        run: |
          ssh ec2-user@${{ EC2_PUB_IP }} 'docker run -d --name "app_container" -p 4000:4000 ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:{{ env.ECR_IMAGE_TAG }}'
